### GET request to get all providers
GET http://localhost:3500/providers/global
Content-Type: application/json

{
  "language": "fr-FR",
  "region": "BE"
}

### GET request to get user providers
GET http://localhost:3500/providers/personal
Authorization: Bearer 1bd4e66f6456d4e39c8a7ae08b9485be14700d3ddc1918befad349fb57fdf3857faededfff46afd2787ad7ee8be5f655
Content-Type: application/json

### POST request to add user providers
POST http://localhost:3500/providers/personal
Authorization: Bearer dfe65e8628d82790a9eea6f1c563708e9f9ea09f780c1e3328de01f0c5f6e7fea5aa3da9b7208f8eea8b83d1081d6570
Content-Type: application/json

{
  "providerId": [283]
}

### GET request to get all providers
GET http://localhost:3500/providers
Authorization: Bearer a9fa45ca810d25bf2ffb2b62aaca4dce663e1013642d5e173b6922ed75a0210aa148e68a55ee6a1a840ed87ea8d1848b
Content-Type: application/json
